
swagger: "2.0"
info:
  description: "VAP Final Project"
  version: "1.0.0"
  title: "Product Inventory "
host: petstore.swagger.io
basePath: "/v2"

tags:
- name: Manager
- name: Inventory
- name: Products 



schemes:
- "http"

paths:
  /item:
      
    post:
      tags:
      - "Manager"
      summary: "adding new item to the inventory"
      operationId: "additem"
      consumes:
        - "application/json"      
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/ITEM"
      responses:
        200:
          description: Succesfully adding the item
          schema:
            type: object
            properties:
              success: 
                type: boolean
              id: 
                type: number
        405:
          description: "Invalid input"
      
  /item/{itemId}/uploadImage:
  
    post:
      tags:
      - "Manager"
      summary: "uploads an image of the item"
      description: ""
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "itemId"
        in: "path"
        description: "ID of item to update"
        required: true
        type: "integer"
        format: "int64"
      - name: "additionalMetadata"
        in: "formData"
        description: "Additional data to pass to server"
        required: false
        type: "string"
      - name: "file"
        in: "formData"
        description: "file to upload"
        required: false
        type: "file"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
      x-swagger-router-controller: "Item"
      
  /item/{itemid}:
    get:
      tags:
        - Inventory
      consumes:
        - "application/json"
      summary: Find item by ID
      description: Returns a single Item
      operationId: getItemById
      parameters:
        - name: itemid
          in: path
          description: ID of pet to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ITEM'
        '400':
          description: Invalid ID supplied
        '404':
          description: ITEM not found
    put :
      tags:
        - Manager
      summary: Update an existing item
      description: ''
      operationId: updateProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - required: true
          in: path
          name: itemid
          type: string
        - required: true
          in: body
          name: body
          description: Items that are modified
          schema :
            $ref: '#/definitions/ITEM'
      responses:
        '200':
          description: item updated 
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
    delete:  
      tags:
        - Manager
      summary: Deletes a item
      description: ''
      operationId: deleteItem
      produces:
        - application/json
      parameters:
        - name : itemid 
          in: path
          description: Item id to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Product deleted
        '400':
          description: Invalid ID supplied
        '404':
          description: Item not found
          
  /category:
    post:
      tags:
        - Manager
      summary: Add a new category to the store listing
      consumes:
        - "application/json"
      parameters:
        - name: category
          in: body
          description: New Category 
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        '200':
          description: Succesful
          schema:
            type: object
            properties:
              success: 
                type: boolean
              id: 
                type: number
              url:
                type: string
        '400':
          description: Error
          schema:
            type: object
            properties:
              success: 
                type: boolean
              message: 
                type: string
    put :
      tags:
        - Manager
      summary: Update category to the store listing
      consumes:
        - "application/json"
      parameters:
        - name: category
          in: body
          description: Update Category 
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        '200':
          description: Category updated 
        '400':
          description: Invalid Category value
        '404':
          description: Category not found
              
  /item/findByStatus:
    get:
      tags:
        - Inventory
      summary: Finds Items by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findItemByStatus
      produces:
        - application/xml
        - application/json
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: true
          type: array
          items:
            type: string
            enum:
              - available
              - unavailable
            default: available
          collectionFormat: multi
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/ITEM'
        '400':
          description: Invalid status value
          
  /item/Brand:
    get:
      tags:
        - Inventory
      summary: Finds Items by Brand
      description: Multiple status values can be provided with comma separated strings
      operationId: findItemByBrand
      produces:
        - application/xml
        - application/json
      parameters:
        - name: brand
          in: query
          description: Brand Choice
          required: true
          type: string

      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/ITEM'
        '400':
          description: Invalid Brand value
          

          
  /item/Category:
    get:
      tags:
        - Inventory
      summary: Finds Items by Category
      description: Multiple status values can be provided with comma separated strings
      operationId: findItemByCategory
      produces:
        - application/xml
        - application/json
      parameters:
        - name: category
          in: query
          description: Category 
          required: true
          type: string

      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/ITEM'
        '400':
          description: Invalid Catergory value        
          
          
  /Price/{itemid}: 
    get:
      tags: 
        - Products
      summary: "Price of the Item with category tax"
      parameters:
        - name: itemid
          type: number
          format: int64
          minimum: 1
          in: path
          required: true
          description: The ID of the product
      produces: 
        - application/json
      responses:
        '200':
          description: Getting the detailed prices of the object
          schema:
            type: object
            properties:
              itemid:
                type: number
                format: int64
              price:
                type: number
                format: float64
              category:
                $ref: '#/definitions/Category'
                
        '404':
          description: Item not found

  /Pricerange/item: 
    get:
      tags:
        - Inventory
      summary: Finds Items in the price range
      description: Multiple status values can be provided with comma separated strings
      operationId: findItemByPrice
      produces:
        - application/xml
        - application/json
      parameters:
        - name: brand
          in: query
          description: Brand Choice
          required: true
          type: string

      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/ITEM'
        '400':
          description: Invalid Brand value
  
  /metadata/{itemid}: 
    get:
      tags: 
        - Products
      summary: "extra info about the item of the Item"
      parameters:
        - name: itemid
          type: number
          format: int64
          in: path
          required: true
          description: The ID of the product
      produces: 
        - application/json
      responses:
        '200':
          description: Getting the quantity of the item 
          schema:
            type: object
            properties:
              itemid:
                type: number
                format: int64
              metadata :
                type: object
                additionalProperties:
                  type: string
        '404':
          description: Item not found
          
  /Quantity/{itemid}: 
    get:
      tags: 
        - Products
      summary: "Quantity of the Items"
      parameters:
        - name: itemid
          type: number
          format: int64
          in: path
          required: true
          description: The ID of the product
      produces: 
        - application/json
      responses:
        '200':
          description: Getting the quantity of the item 
          schema:
            type: object
            properties:
              itemid:
                type: number
                format: int64
              quantity:
                type: number
        '404':
          description: Item not found
    put:
      tags: 
        - Products
      summary: "update quantity of the Items"
      parameters:
        - name: itemid
          type: number
          format: int64
          in: path
          required: true
          description: The ID of the product
      produces: 
        - application/json
      responses:
        '200':
          description: Getting the quantity of the item 
          schema:
            type: object
            properties:
              itemid:
                type: number
                format: int64
              quantity:
                type: number
        '404':
          description: Item not found
          
  /brands:
    get:
      tags: 
        - Products
      summary: Brands in the inventory
      responses:
        "200":
          description: successful
          schema:
            $ref: '#/definitions/Brands'
        "404":
          description: Brand not found


definitions:
  Category: 
    type: "object"
    properties:
      name:
        type: "string"
      tax:
        type: number
    example:
      name: "name"
      tax : 5

  Brands:
    type: "object"
    properties:
      name:
        type: "string"
    example:
      name: "name"
      
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    example:
      name: "name"
      id: 1
  
  ITEM:
    type: "object"
    required : 
      - id 
      - name 
    properties:
      id:
        type: "integer"
        format: "int64"
      category:
        $ref: "#/definitions/Category"
      brand:
        $ref: "#/definitions/Brands"
      price:
        type: number
      sku:
        type: number 
      quantity:
        type: number
      name:
        type: "string"
        example: "shoes"
      photoUrls:
        type: "array"
        xml:
          name: "photoUrl"
          wrapped: true
        items:
          type: "string"
      tags:
        type: "array"
        xml:
          name: "tag"
          wrapped: true
        items:
          $ref: "#/definitions/Tag"
      metadata:
        type: object
        additionalProperties:
          type: string
      status:
        type: "string"
        description: "item status in the store"
        enum:
        - "available"
        - "pending"
        - "sold"
      digital:
        type : boolean
    example:
      name: "shoes"
      id: 0
      brand:
        name: "nike"
      price:
        name: 1000
      tags:
      - name: "name"
        id: 1
      status: "available"
      photoUrls:
      - "photoUrlssome"
      - "photoUrlssome"
  
    
      
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
    example:
      code: 0
      type: "type"
      message: "message"
